# Generated by Django 3.0.2 on 2020-02-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='user',
            new_name='owner',
        ),
    ]
